version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: gitsubmodule
    schedule:
      interval: 'daily'
    directory: /

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 4
  # - package-ecosystem: pip
  #   directory: "/"
  #   schedule:
  #     interval: 'daily'
  #   open-pull-requests-limit: 4
